<div class="container">
<div class="col-lg-8 mx-auto">
        </div>
      </div>

<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
    <form action="" method="post" enctype="multipart/form-data">
    <input type="hidden" name="event_number" value="<?php echo $eventdel->event_number;?>">
    <h1> Are you sure you want to delete event?</h1>
    <button type="submit" class="btn btn-info">Yes</button>
    <a href="<?php echo $this->url->getBaseUri(); ?>/event/show" class="btn btn-warning">No</a>

</form>
    </div>
    <div class="col-sm">
    </div>
  </div>